topics:
  github-actions:
    email_subscribers:
      - "mrangelcruz@gmail.com"
      - "anghotpekpek@gmail.com"
  deployment-notifications:
    email_subscribers:
      - "mrangelcruz@gmail.com"

environment:
  Development:
    color: grey
  Staging:
    color: black
  Production:
    color: pink