name: Build and Push Docker Image

on:
  push:
    branches:
      - dockerhub  # or your deployment branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:${{ github.sha }}

      - name: Create Octopus Release
        uses: OctopusDeploy/create-release-action@v3
        with:
          api_key: ${{ secrets.OCTOPUS_API_KEY }}
          server: ${{ secrets.OCTOPUS_SERVER }}
          space: "Default"
          project: "flask-app"
          release_number: ${{ github.sha }}


      - name: Deploy Octopus Release
        env:
          OCTOPUS_API_KEY: ${{ secrets.OCTOPUS_API_KEY }}
          OCTOPUS_SERVER: ${{ secrets.OCTOPUS_SERVER }}
          OCTOPUS_SPACE: "Spaces-1"
          OCTOPUS_PROJECT: "flask-app"
          OCTOPUS_ENVIRONMENT: "Production"
          RELEASE_NUMBER: ${{ github.sha }}
        run: |

          curl -s -H "X-Octopus-ApiKey: $OCTOPUS_API_KEY" "$OCTOPUS_SERVER/api/Spaces-1/projects" | jq '.Items[] | {Name, Id}'

        
          # curl -s -H "X-Octopus-ApiKey: $OCTOPUS_API_KEY" "$OCTOPUS_SERVER/api/$OCTOPUS_SPACE/environments"

          # # Get Release ID
          # RELEASE_ID=$(curl -s -H "X-Octopus-ApiKey: $OCTOPUS_API_KEY" "$OCTOPUS_SERVER/api/$OCTOPUS_SPACE/projects/$OCTOPUS_PROJECT/releases/$RELEASE_NUMBER" | jq -r .Id)

          # # Get Environment ID
          # ENVIRONMENT_ID=$(curl -s -H "X-Octopus-ApiKey: $OCTOPUS_API_KEY" "$OCTOPUS_SERVER/api/$OCTOPUS_SPACE/environments" | jq -r ".Items[] | select(.Name==\"$OCTOPUS_ENVIRONMENT\") | .Id")

          # # Trigger Deployment
          # curl -X POST "$OCTOPUS_SERVER/api/$OCTOPUS_SPACE/deployments" \
          #   -H "X-Octopus-ApiKey: $OCTOPUS_API_KEY" \
          #   -H "Content-Type: application/json" \
          #   -d "{
          #     \"ReleaseId\": \"$RELEASE_ID\",
          #     \"EnvironmentId\": \"$ENVIRONMENT_ID\"
          #   }"
