name: Build and Push Docker Image
on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # The magic happens here! ✨
    - name: Configure AWS Credentials and ECR Login
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::220682131352:role/ECR-full-permission-for-GitHub
        aws-region: us-east-1
        # This tells the action to perform the ECR login automatically
        ecr-repository: ${{ secrets.ECR_REPO_URI }}

    - name: Echo values for debugging
      run: |
        echo "ECR Repo URI: ${{ secrets.ECR_REPO_URI }}"
        echo "GitHub SHA: ${{ github.sha }}"

    - name: Build and Push Docker image
      run: |
        IMAGE_TAG=$(echo ${{ github.sha }} | cut -c1-7)
        docker build -t ${{ secrets.ECR_REPO_URI }}:${IMAGE_TAG} .
        docker push ${{ secrets.ECR_REPO_URI }}:${IMAGE_TAG}
