name: Build and Push Docker Image

on:
  push:
    branches:
      - dockerhub  # or your deployment branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:${{ github.sha }}

      - name: Create Octopus Release
        uses: OctopusDeploy/create-release-action@v3
        with:
          api_key: ${{ secrets.OCTOPUS_API_KEY }}
          server: ${{ secrets.OCTOPUS_SERVER }}
          space: ${{ secrets.OCTOPUS_SPACE }}
          project: "Flask App Deployment"
          release_number: ${{ github.sha }}
          deploy_to: "Production"


    # - name: Trigger Octopus Deploy
    #   uses: OctopusDeploy/push-package-action@v1
    #   with:
    #     api_key: ${{ secrets.OCTOPUS_API_KEY }}
    #     server: ${{ secrets.OCTOPUS_SERVER_URL }}
    #     space: ${{ secrets.OCTOPUS_SPACE }}
    #     project: ${{ secrets.OCTOPUS_PROJECT }}
    #     deploy_to: ${{ secrets.OCTOPUS_ENVIRONMENT }}
    #     release_number: ${{ github.run_number }}
    #     package_version: ${{ env.IMAGE_TAG }}
    #     # Optional: Add `git_ref` or `branch` metadata here if needed
