name: Build and Push Docker Image
on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::220682131352:role/ECR-full-permission-for-GitHub
        aws-region: us-west-2

    # This is the new, correct step for ECR login
    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO_URI }}
      env:
        AWS_REGION: us-west-2

    - name: Build and Push Docker image
      run: |
        IMAGE_TAG=$(echo ${{ github.sha }} | cut -c1-7)
        docker build -t ${{ secrets.ECR_REPO_URI }}:${IMAGE_TAG} .
        docker push ${{ secrets.ECR_REPO_URI }}:${IMAGE_TAG}
