name: Build and Push Docker Image
on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::123456789012:role/my-github-actions-ecr-role
        aws-region: us-east-1

    - name: Build Docker image
      run: |
        IMAGE_TAG=$(echo ${{ github.sha }} | cut -c1-7)
        docker build -t ${{ secrets.ECR_REPO_URI }}:${IMAGE_TAG} .
        docker tag ${{ secrets.ECR_REPO_URI }}:${IMAGE_TAG} ${{ secrets.ECR_REPO_URI }}:latest

    - name: Push Docker image to ECR
      run: |
        docker push ${{ secrets.ECR_REPO_URI }}:latest
        docker push ${{ secrets.ECR_REPO_URI }}:${{ github.sha }}
